# Generated by Django 2.2.1 on 2019-06-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20190612_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='massage',
            field=models.CharField(choices=[('SW', 'Swedish'), ('DT', 'Deep Tissue')], default=None, max_length=2, null=True),
        ),
    ]
