# Generated by Django 2.2.1 on 2019-08-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='black_out',
            field=models.BooleanField(default=False),
        ),
    ]
